# Generated by Django 3.2 on 2022-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
